### ISSUE TITLE
SegFault 11 when running on osx 10.12.6

### ISSUE THREAD

**Issue by dstanley** [arduboy-emulator/sim-arduboy#3]
./sim_arduboy test.hex 
Keymap: 1073741906,1073741905,1073741904,1073741903,122,120
Segmentation fault: 11

I'm sure its an environment issue. I used brew to install libraries and all looked to succeed as expected. Am I missing any additional dependencies?

Thanks

**Comment by dxxb** [comment]
> Am I missing any additional dependencies?

I doubt it. if it builds successfully all deps are there.

> ./sim_arduboy test.hex

Can you share the test .hex file and its source code so I can reproduce the issue? Thank you.

**Comment by dstanley** [comment]
Using Arduino IDE 1.8.5  + Leonardo board. Thx.
[HelloWorld.zip](https://github.com/dxxb/sim-arduboy/files/1482531/HelloWorld.zip)

**Comment by dxxb** [comment]
Works here with Arduino IDE 1.8.4 (can't switch to 1.8.5 right now) + Leonardo board:
```
$ ./sim_arduboy ~/Downloads/HelloWorld/HelloWorld.ino.leonardo.hex
Keymap: 1073741906,1073741905,1073741904,1073741903,122,120
SSD1306: 37uS is 592 cycles for your AVR
SSD1306: 1uS is 16 cycles for your AVR
```

Does the OS show you a windows with a crash dump you could post? Thanks

**Comment by dstanley** [comment]
I went digging and found a crash report. Hope it helps!
[sim_arduboy_2017-11-14-171735_dstanley-mb.crash.zip](https://github.com/dxxb/sim-arduboy/files/1482722/sim_arduboy_2017-11-14-171735_dstanley-mb.crash.zip)

**Comment by dxxb** [comment]
The segfault happens here: https://github.com/dxxb/sim-arduboy/blob/386bcd475ce9f1e09bdc1d87da6e60aca9040a59/arduboy_avr.c#L175

My guess at this stage is that simavr reads back invalid offset and size from the .hex file. Can you try the IDE 1.8.4?
