### ISSUE TITLE
[Feature Request] Add ability to scale/resize window 

### ISSUE THREAD

**Issue by vbauer** [arduboy-emulator/sim-arduboy#4]
It would be create to have ability to resize window to scale output area. In the current version it is very small..

<img width="263" alt="screen shot 2018-09-15 at 22 35 51" src="https://user-images.githubusercontent.com/578021/45587981-bb35b880-b937-11e8-8411-c3141de8fe49.png">

Actually it is possible to resize window, but output area is the same as initial

**Comment by dxxb** [comment]
Hi, please try the -p command line switch to increase pixel size. For instance you can use -p 2 or -p 3. Please close this issue if -p suits your needs. Thank you.

**Comment by vbauer** [comment]
Oops, shame on me.. Thank you very much!

**Comment by dbrignoli** [comment]
No worries, you are welcome.

**Comment by dxxb** [comment]
No worries, you are welcome.
